const mongoose = require("mongoose");
const validator = require("validator");
const bcrypt = require("bcrypt");
const UserSchema = new mongoose.Schema({
  name: {
    type: String,
    unique: true,
    maxlength: [20, "Name must be within 20 characters"],
    minlength: [4, "Name must be atleast 5 character long"],
    required: [true, "Nume is a must"],
  },
  email: {
    type: String,
    required: [true, "E-mail is a must. Please fill it ."],
    validate: [validator.isEmail, "Please provide Valid email"],
    unique: true,
    lowercase: true,
  },
  gender: String,
  mobilenumber: {
    type: Number,
    unique: true,
    required: [true, "Contact number is a must"],
  },
  dob: Date,
  password: {
    type: String,
    minlength: [8, "Password must be at least 8 characters long."],
    required: [true, "Password is a must"],
    select: false,
  },
  passwordConfirm: {
    type: String,
    minlength: [8, "Password must be at least 8 characters long."],
    required: [true, "Password is a must"],
    validate: {
      // this runs only on 'save' & 'create'
      validator: function (el) {
        return el === this.password;
      },
      mesasage: "Confirm password must match with password",
    },
  },
});

UserSchema.pre("save", async function (next) {
  //if password field is not modified then we don't have to hash the password
  if (!this.isModified("password")) return next();

  // Hashing the password with the cost of 12 (salt is autogenerated becauswe we didn't assign it)
  this.password = await bcrypt.hash(this.password, 12); // await because this returns promise

  //Removing this because it was just for confirmation from user and we will not hash this also
  this.passwordConfirm = undefined;
  console.log(this.password);
  next();
});

UserSchema.methods.correctPassword = async function (
  savedPassword,
  userPassword
) {
  return bcrypt.compare(savedPassword, userPassword);
};
const User = mongoose.model("User", UserSchema);
module.exports = User;
